### ISSUE TITLE
Parse (or ignore) default settings

### ISSUE THREAD

**Issue by makmic** [makandra/rascal#5]
Hi :wave:,

I recently noticed this exception when trying to start a rascal shell:
> missing config for 'default.image'

The root case seems to be that I am using [gitlab's default value group](https://docs.gitlab.com/ee/ci/yaml/#default) which is interpreted as a job definition by rascal:

```yml
default:
  tags:
    -  foo
  retry:
    max: 2
    when:
      - unknown_failure # Retry when the failure reason is unknown.
```

I think rascal should either parse the `default` group and apply its settings to all jobs - or simply ignore it.

## Failing feature
```feature
  Scenario: Don't crash when there is a default group
    Given the following gitlab-ci config:
      """
      default:
        retry: 1
      job:
        image: job-image:latest
      """
      And the docker image "job-image:latest" exists

    When I successfully run `rascal shell job`
```
